# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7310324d85f12bfc4abfe3176d4289a27368e11663df7bd762600ee6ba9b4db1dcd52f98e57cd63a14408c2fbac942d6f82677c4b9207d4724d4f028d87a8f39

test:
  secret_key_base: 68a4f26bc46dbd0be238db2c56c4605ffa2ec43372358a6508fe1b61f9da1c3bb23e1618dd530db94f3d2794bea921d603ac807b716353b924e3b5c6322c8970

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
